global:
  scrape_interval: 10s 
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'

rule_files:
  - '/etc/prometheus/rules/alerts/errors-rules.yml'
  - '/etc/prometheus/rules/alerts/instance-health-rules.yml'
  - '/etc/prometheus/rules/recording/ovp-metrics-rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - 'prometheus:9090'
  - job_name: 'service'
    static_configs:
      - targets: 
        - 'service:8080'
